name: WE
description: A flutter app that aims to make plastic transformation convenient and gamified.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  firebase_database: ^6.0.0
  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.2
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^1.0.3
  convex_bottom_bar: ^2.5.1+1
  liquid_progress_indicator: ^0.3.2
  syncfusion_flutter_charts: ^18.4.30
  google_nav_bar: ^2.0.0
  flutter_svg: ^0.19.1
  functional_widget_annotation: ^0.8.0
  http: ^0.12.0+1
  json_serializable: ^3.3.0
  getwidget: ^1.2.4
  flutter_icons: ^1.0.0+1
  google_sign_in: ^4.4.0
  get_it: ^4.0.1
  firebase_storage: ^7.0.0
  async: ^2.0.8
  cloud_firestore: ^0.16.0+1
  nice_button: ^0.1.7
  carousel_slider: ^3.0.0
  animated_text_kit: ^3.1.2
  dio: 1.0.0
  path: ^1.7.0
  geolocator: ^5.3.1
  timeline_tile: ^1.0.0
  image_picker: ^0.5.3+2
  introduction_screen: ^1.0.9
  permission_handler: ^5.1.0+2
  shared_preferences: ^0.5.12+4
  after_layout: ^1.0.7+2
  pin_code_fields: ^6.1.0
  shimmer: ^2.0.0
  lottie: ^0.7.0+1
  easy_localization: ^1.3.5
  splashscreen: ^1.3.5
  social_share: ^2.0.6
  screenshot: ^0.3.0
  double_back_to_close: ^1.0.2
  qr_code_scanner: ^0.3.5
  bubble: ^1.1.9+1
  flutter_blue: ^0.7.3
  flutter_spinkit: ^5.1.0
  confetti: ^0.6.0
  provider: ^6.0.1
  youtube_player_iframe: ^2.2.2
  youtube_player_flutter: ^8.0.0


dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Panthera
      fonts:
        - asset: assets/TextStyles/Panthera/PantheraRegular-MVZ9J.ttf
    - family: Montserrat_Alternates
      fonts:
        - asset: assets/TextStyles/Montserrat_Alternates/MontserratAlternates-Regular.ttf
    - family: Bracelet
      fonts:
        - asset: assets/TextStyles/Bracelet/CustomIcons.ttf
  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/
    - assets/Images/
    - assets/Images/Entertainment/
    - assets/Images/Offers/
    - assets/Images/Feeds/
    - assets/Images/People/
    - assets/Images/BottomNavigation/
    - assets/Images/Badges/
    - assets/Images/Badges/Locked/
    - assets/Images/Badges/Unlocked/
    - assets/Images/Onboarding/
    - assets/translations/

